### ISSUE TITLE
Make all arrays multiline when writing the configuration file

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#310]
### Feature description

Per title.

### Value and/or benefit

Below is the components section of a fresh configuration file created with `ragna init` when selecting all builtin options:

```toml
[components]
source_storages = ["ragna.source_storages.Chroma", "ragna.source_storages.RagnaDemoSourceStorage", "ragna.source_storages.LanceDB"]
assistants = ["ragna.assistants.Claude", "ragna.assistants.ClaudeInstant", "ragna.assistants.RagnaDemoAssistant", "ragna.assistants.GeminiPro", "ragna.assistants.GeminiUltra", "ragna.assistants.Mpt7bInstruct", "ragna.assistants.Mpt30bInstruct", "ragna.assistants.Gpt4", "ragna.assistants.Gpt35Turbo16k"]
```

This is really hard to read and edit and will only get worse with #303, #307, and whatever other components we add in the future.

Instead, I want this to look like

```toml
[components]
source_storages = [
    "ragna.source_storages.Chroma",
    "ragna.source_storages.RagnaDemoSourceStorage",
    "ragna.source_storages.LanceDB",
]
assistants = [
    "ragna.assistants.Claude",
    "ragna.assistants.ClaudeInstant",
    "ragna.assistants.RagnaDemoAssistant",
    "ragna.assistants.GeminiPro",
    "ragna.assistants.GeminiUltra",
    "ragna.assistants.Mpt7bInstruct",
    "ragna.assistants.Mpt30bInstruct",
    "ragna.assistants.Gpt4",
    "ragna.assistants.Gpt35Turbo16k",
]
```
