### ISSUE TITLE
How are we going to handle configuration?

### ISSUE THREAD

**Issue by pmeier** [Quansight/ragna#50]
## Status quo

Right now we have fully dynamic configuration as Python object:

https://github.com/Quansight/ragna/blob/b32c2d964f0da07e7bf5bbef8ef8ba0fad701e7a/ragna/core/_config.py#L21-L25

This is taken by the `ragna.core.Rag` object

https://github.com/Quansight/ragna/blob/b32c2d964f0da07e7bf5bbef8ef8ba0fad701e7a/ragna/core/_rag.py#L24-L27

and thus provides maximum flexibility.

Outside of the Python API, users can provide their own configuration through the CLI with the `-c` / `--config` option:

https://github.com/Quansight/ragna/blob/b32c2d964f0da07e7bf5bbef8ef8ba0fad701e7a/ragna/_cli.py#L41-L44

`Config.load_from_source` takes a path string, imports the module and takes the config object as specified.

To register RAG components, i.e. custom source storages or assistants, users can put a decorator on the class they have implemented

https://github.com/Quansight/ragna/blob/b32c2d964f0da07e7bf5bbef8ef8ba0fad701e7a/ragna/core/_config.py#L93

like

```python
config = ragna.core.Config(...)

@config.register_component
class MyCustomSourceStorage(ragna.core.SourceStorage):
    ...

```

## Problems

As specified above, defining the configuration purely in Python gives users maximum flexibility. But this also means creep over time. Because it is so convenient, at some point the configuration might even contain actual logic. We want to avoid for the sanity of the human who needs to deploy ragna beyond the experimentation use case.

However, we can't go fully static. Meaning, just having a declarative configuration file is not enough. We need some way for users to "include" extensions they have written and other Python objects that will be used in the RAG workflow.

## Potential solution

We could go with middle ground solution, e.g. a `config.toml` file for all the static options as well as the option to specify the location of Python objects that we'll load at runtime. For example

```toml
[core]
queue_url = "redis://127.0.0.1:6379"

source_storages = [
    "ragna.source_storage.RagnaDemoSourceStorage",
]

assistants = [
    "ragna.source_storage.RagnaDemoSourceStorage",
    "/path/to/my/package.py::sub.subsub.MyAssistant",
]

[api]
url = "http://127.0.0.1:31476"
```

Parsing this file into Python config is straightforward. And since we already depend on `pydantic`, validating is simple as well.

Thus, that should give us best of both worlds. We could also implement a "CLI wizard" to help the user define the config file.
